"""The skill: what an agent is told, rendered from what the machinery declares.

An agent that loads the skill and an agent that runs the CLI must be doing the same thing.
They were not. The skill was written by hand from memory of this repository and then drifted
from it: it omitted `in-tension-with` entirely, still called `dissociates-with` an opposition
after the #125 ruling moved it out, and offered an `epistemic` value (`contested`) that no
claim file uses. A tree built by following it would have used the retired relation for the
case the ruling split off.

That is the same failure `contract.py` exists to prevent one level down, so this is the same
answer: the skill is *rendered*. Prose that carries judgment — what to look for in a paper,
which pairs of relations people confuse, what to report when handing a structure over — is
written by hand in `docs/skill/`. Everything that is declared somewhere is substituted into it
at build time from the declaration:

    scripts/relations.py           relations, direction, corpus examples, confusable pairs
    scripts/check_relations.py     the rules the gate enforces, so advice and gate agree
    claim_graphs/vocabulary.py     roles, claim types, confidence
    schema/to_claim_set.py         the closed value sets the interchange form accepts
    pipeline/layers.yaml           the sequence, so a runbook cannot list a layer that moved
    contract.py                    the vocabulary the model is actually sent, verbatim

`skill --check` fails when the committed skill is not what those sources generate, and
`make check` runs it. An unknown `{{token}}` fails generation rather than being rendered as a
word, the convention the site build already uses.

Like the contract, some tokens quote real claims, so a corpus checkout is needed to regenerate
or verify. The rendered skill is committed and ships without one.
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import yaml

from . import contract, vocabulary

SKILL_DIR = "skills/claim-structures"
SOURCE_DIR = "docs/skill"

FILES = (
    "SKILL.md",
    "references/vocabulary.md",
    "references/relations.md",
    "references/checks.md",
    "references/presentation.md",
    "workflows/analyze-paper.md",
    "workflows/spec-paper.md",
    "workflows/design-experiment.md",
)

NOTE = ("<!-- Generated by `claim-graphs skill --write` from docs/skill/{name} and the "
        "declarations named in extract/claim_graphs/skill.py. Do not edit: edit the source or "
        "the declaration and regenerate. `make check` fails when this file is not what they "
        "generate. -->")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _script(root: Path, name: str):
    """A module under `scripts/`, loaded by path: they are scripts, not a package."""
    spec = importlib.util.spec_from_file_location(name, root / "scripts" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


def _layers(root: Path) -> dict:
    return yaml.safe_load((root / "pipeline" / "layers.yaml").read_text(encoding="utf-8"))


def _chain(root: Path, target: str) -> list[dict]:
    """The layers `target` needs, in dependency order — the walk `pipeline.py run` makes."""
    by_id = {ly["id"]: ly for ly in _layers(root)["layers"]}
    out: list[dict] = []
    seen: set[str] = set()

    def visit(lid: str):
        if lid in seen or lid not in by_id:
            return
        seen.add(lid)
        ly = by_id[lid]
        for dep in ly.get("needs", []):
            visit(dep)
        if ly.get("scope") != "corpus":
            out.append(ly)

    visit(target)
    return out


# ── tokens ───────────────────────────────────────────────────────────────
#
# Each returns the markdown that replaces `{{name}}`. A token that needs a corpus says so by
# letting contract.py's FileNotFoundError out: the caller reports the missing corpus once.


def t_generated_note(root: Path, name: str) -> str:
    return NOTE.format(name=name)


def t_relations_table(root: Path, name: str) -> str:
    rel = _script(root, "relations")
    out = ["| Relation | What it asserts | Direction |", "|:--|:--|:--|"]
    for r in sorted(rel.EDGE_KEYS):
        out.append(f"| `{r}` | {rel.DESCRIPTIONS[r]} | {rel.DIRECTION.get(r, '—')} |")
    out += ["", f"{len(rel.EDGE_KEYS)} relations. The vocabulary is closed: a relation outside "
                "it is invisible to every query and every export."]
    return "\n".join(out)


def t_relations_directions(root: Path, name: str) -> str:
    rel = _script(root, "relations")
    return "\n".join(f"- `A {r} B` — {rel.DIRECTION[r]}." for r in sorted(rel.DIRECTION))


def t_relations_examples(root: Path, name: str) -> str:
    rel = _script(root, "relations")
    out = []
    for r in sorted(rel.EDGE_KEYS):
        ex = rel.EXAMPLE.get(r)
        if not ex:
            out.append(f"- `{r}` — no use in the corpus yet.")
            continue
        paper, src, tgt = ex
        s = contract._claim(root, paper, src)
        if tgt == "*":
            out.append(f"- `{r}`: `{src}` → `*` — “{s['claim']}”")
        else:
            t = contract._claim(root, paper, tgt)
            out.append(f"- `{r}`: `{src}` → `{tgt}`\n"
                       f"  - source: “{s['claim']}”\n  - target: “{t['claim']}”")
    return "\n".join(out)


def t_relations_confusable(root: Path, name: str) -> str:
    rel = _script(root, "relations")
    return "\n\n".join(f"**`{a}` versus `{b}`.** {why}" for a, b, why in rel.CONFUSABLE)


def t_claim_types(root: Path, name: str) -> str:
    out = ["| `claim-type` | Meaning |", "|:--|:--|"]
    out += [f"| `{n}` | {m} |" for n, m in vocabulary.CLAIM_TYPES]
    return "\n".join(out)


def t_roles(root: Path, name: str) -> str:
    out = ["| `role` | The work it does | Typical `claim-type` |", "|:--|:--|:--|"]
    for r in vocabulary.ROLES:
        first = " ".join(str(r["definition"]).split()).split(". ")[0].rstrip(".")
        out.append(f"| `{r['role']}` | {first} | `{r['typical_claim_type']}` |")
    return "\n".join(out)


def t_epistemic(root: Path, name: str) -> str:
    tcs = importlib.util.spec_from_file_location(
        "to_claim_set", root / "schema" / "to_claim_set.py")
    mod = importlib.util.module_from_spec(tcs)
    tcs.loader.exec_module(mod)  # type: ignore[union-attr]
    vals = ", ".join(f"`{v}`" for v in sorted(mod.STRENGTH))
    return (f"{vals} — the set `schema/to_claim_set.py` accepts when converting a claim file to "
            "the interchange form.\n\n"
            "What `epistemic` *means* is an open question (`epistemic-vocab`, issue #20): on "
            "some claims it records how strongly the evidence supports the proposition, and on "
            "others it restates the role — a hypothesis marked `weak` because hypotheses are "
            "hypotheses, not because anything was measured. Record support strength, and do not "
            "read the corpus's existing values as consistent.")


def t_stances(root: Path, name: str) -> str:
    rel = _script(root, "relations")
    mean = {
        "asserts": "the document claims the proposition is true — the default when absent",
        "entertains": "raised as a candidate, not asserted. What a control's `rules-out` needs "
                      "as its target",
        "rejects": "the document argues it is false",
        "attributes": "someone else asserts it and this document reports that. Requires a "
                      "`source`",
    }
    out = ["| `stance` | Meaning |", "|:--|:--|"]
    out += [f"| `{s}` | {mean.get(s, '')} |" for s in sorted(rel.STANCES)]
    return "\n".join(out)


def t_check_rules(root: Path, name: str) -> str:
    chk = _script(root, "check_relations")
    out = ["These are rejected by `scripts/check_relations.py`, which `make check` runs. They "
           "are not advice: a tree that breaks one does not pass the gate.", ""]
    for i, (rid, rejects, fix) in enumerate(chk.RULES, 1):
        out.append(f"{i}. **{rejects}** ({rid})  \n   {fix}")
    out += ["", "Reported as a warning rather than an error:", ""]
    for rid, rejects, fix in chk.WARNS:
        out.append(f"- **{rejects}** ({rid}) — {fix}")
    out += ["", "```bash", "python3 scripts/check_relations.py --rules        # this list, from the checker",
            "python3 scripts/check_relations.py <paper> --warnings", "make check", "```"]
    return "\n".join(out)


def t_agent_runbook(root: Path, name: str) -> str:
    """The claim-tree chain as an agent runs it: same layers, same prompts, no API key."""
    chain = _chain(root, "claim-tree")
    out = [
        "The sequence below is generated from `pipeline/layers.yaml`, which is the same "
        "declaration `pipeline.py run` walks. Do not work from a remembered layer list: a "
        "layer that is added, renamed or reordered changes this file and nothing else.",
        "",
        "### Say where the graph is first",
        "",
        "The machinery and the graph are two checkouts. This repository holds the layers, the "
        "prompts and the runner; `runs/<paper>/` and `claims/<paper>/` belong to whoever "
        "asserts the graph — a paper's own repository, or a corpus of readings of other "
        "people's papers. Name the graph's root or every layer looks for its inputs beside the "
        "machinery and reports that `prepare` has not run.",
        "",
        "```bash",
        "export CLAIM_GRAPHS_ROOT=/path/to/the/graph        # where runs/ and claims/ live",
        "export CLAIM_GRAPHS_CORPUS_DIR=$CLAIM_GRAPHS_ROOT/claims",
        "```",
        "",
        "Run the commands below from this repository. A layer's `reads:` — its prompts, its "
        "scripts — resolves here; everything it `produces:` resolves in the graph root, and "
        "the ledger a run appends to is the graph's, not the machinery's. Leave "
        "`CLAIM_GRAPHS_ROOT` unset and both are this checkout, which is what a repository "
        "holding the corpus and the machinery together means.",
        "",
        "| # | Layer | Asks | Answered by |",
        "|--:|:--|:--|:--|",
    ]
    model_answered = []
    for i, ly in enumerate(chain, 1):
        by = "a model" if ly.get("by_from") else "mechanically, no model call"
        if ly.get("by_from"):
            model_answered.append(ly)
        q = " ".join(str(ly.get("question", "")).split())
        out.append(f"| {i} | `{ly['id']}` | {q} | {by} |")

    out += [
        "",
        "**Mechanical layers** run as declared — nothing to answer:",
        "",
        "```bash",
    ]
    for ly in chain:
        if not ly.get("by_from") and ly.get("command"):
            out.append(f"python3 scripts/pipeline.py run <paper> {ly['id']}")
    out += ["```", "",
            "**Model-answered layers** run as a three-step loop per layer. The prompt is not "
            "described to you; it is handed to you as the bytes the backend would have "
            "received.",
            "",
            "```bash",
            "# 1. emit the exact (system, user) this layer would send, and stop",
            "cd extract && python3 -m claim_graphs.cli <layer> --paper <paper> \\",
            "    --profile subagent --dump-prompt /tmp/<layer>.prompt.txt",
            "",
            "# 2. answer it in a subagent that has been given that file and nothing else.",
            "#    Return JSON only. Write it to /tmp/<layer>.answer.json",
            "",
            "# 3. record the answer through the runner, so it is validated and ledgered",
            "python3 scripts/pipeline.py run <paper> <layer> --no-deps \\",
            "    --answer /tmp/<layer>.answer.json --by \"<model that answered>\" --tokens <n>",
            "```",
            "",
            "in this order:",
            ""]
    for ly in model_answered:
        out.append(f"- `{ly['id']}` — {' '.join(str(ly.get('question', '')).split())}")
    out += [
        "",
        "Three things this loop buys that answering from memory does not. The prompt carries "
        "the rendered contract, so the definitions you work from are the ones the corpus is "
        "built on. `--answer` runs the same validation a backend reply gets, so a malformed "
        "answer fails here rather than three layers downstream. And the ledger records the "
        "inputs by content hash with `by` naming who answered, so the tree has a provenance "
        "record identical in shape to one produced through an API.",
        "",
        "**The three readers must not see each other's output.** `reconcile` grades a claim "
        "`high`, `contested` or `single-source` by how many readers independently surfaced it. "
        "Answer all three in one context and that grade measures nothing — it reports agreement "
        "you manufactured. One subagent per reader, each given only its own dumped prompt.",
    ]
    return "\n".join(out)


def t_layer_table(root: Path, name: str) -> str:
    doc = _layers(root)
    groups = {g: v.get("title", g) for g, v in (doc.get("groups") or {}).items()}
    out = ["| Layer | Group | Asks |", "|:--|:--|:--|"]
    for ly in doc["layers"]:
        q = " ".join(str(ly.get("question", "")).split())
        out.append(f"| `{ly['id']}` | {groups.get(ly.get('group'), '—')} | {q} |")
    return "\n".join(out)


def t_contract_vocabulary(root: Path, name: str) -> str:
    """The contract's vocabulary file, verbatim — what the model is actually sent."""
    body = contract.render_vocabulary(root)
    body = body.replace("# The claim vocabulary\n", "", 1).lstrip("\n")
    return body


TOKENS = {
    "generated-note": t_generated_note,
    "relations-table": t_relations_table,
    "relations-directions": t_relations_directions,
    "relations-examples": t_relations_examples,
    "relations-confusable": t_relations_confusable,
    "claim-types": t_claim_types,
    "roles": t_roles,
    "epistemic": t_epistemic,
    "stances": t_stances,
    "check-rules": t_check_rules,
    "agent-runbook": t_agent_runbook,
    "layer-table": t_layer_table,
    "contract-vocabulary": t_contract_vocabulary,
}

TOKEN_RE = re.compile(r"\{\{([a-z0-9-]+)\}\}")


# ── render, write and check ──────────────────────────────────────────────


def render(name: str, root: Path | None = None) -> str:
    root = root or _repo_root()
    src = root / SOURCE_DIR / name
    if not src.is_file():
        raise FileNotFoundError(f"skill source missing: {src}")
    text = src.read_text(encoding="utf-8")
    if "{{generated-note}}" not in text:
        raise ValueError(f"{SOURCE_DIR}/{name} has no {{{{generated-note}}}} — a rendered file "
                         f"that does not say it is rendered will be edited in place")

    def sub(m: re.Match) -> str:
        tok = m.group(1)
        if tok not in TOKENS:
            raise ValueError(f"{SOURCE_DIR}/{name}: unknown token {{{{{tok}}}}}; "
                             f"known: {', '.join(sorted(TOKENS))}")
        return TOKENS[tok](root, name)

    out = TOKEN_RE.sub(sub, text)
    return out if out.endswith("\n") else out + "\n"


def generated(root: Path | None = None) -> dict[str, str]:
    root = root or _repo_root()
    return {name: render(name, root) for name in FILES}


def write(root: Path | None = None) -> list[Path]:
    root = root or _repo_root()
    out = []
    for name, text in generated(root).items():
        p = root / SKILL_DIR / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
        out.append(p)
    return out


def check(root: Path | None = None) -> list[str]:
    """Names of committed skill files that differ from what the sources generate."""
    root = root or _repo_root()
    stale = []
    for name, text in generated(root).items():
        p = root / SKILL_DIR / name
        if not p.is_file() or p.read_text(encoding="utf-8") != text:
            stale.append(name)
    return stale
