#!/usr/bin/env python3
"""Render the standards mappings from standards.yaml — one table, generated.

    python3 scripts/standards_report.py            # to stdout
    python3 scripts/standards_report.py --write    # docs/schema-mapping/mappings.md

The prose tables under docs/schema-mapping/ were hand-written and had drifted: cito-mapping.md
still documented `dissociates-with` as `cito:disagreesWith`, which the #125 ruling removed and
formats_report.py now asserts is gone, and it listed 14 relations of 21. A mapping nobody can
check against what is exported is a mapping that drifts, so this is generated from the file the
exporters read and `make check` fails when the committed copy is stale.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "extract"))
from claim_graphs import standards  # noqa: E402

MACHINERY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(MACHINERY, "docs", "schema-mapping", "mappings.md")


def render() -> str:
    rels = standards.relations()
    w: list[str] = []
    w.append("# Standards mappings")
    w.append("")
    w.append("<!-- Generated by scripts/standards_report.py from standards.yaml. Do not edit: "
             "edit the table. -->")
    w.append("")
    w.append("Every relation, and what each standard calls it. `—` means the standard has no term "
             "for it, which is information rather than an omission: the alternative is exporting "
             "the nearest predicate and asserting something the relation does not mean.")
    w.append("")
    w.append("| Relation | MIRA | domain → range | CiTO | Discourse Graphs |")
    w.append("|:--|:--|:--|:--|:--|")
    for name in sorted(rels):
        r = rels[name]
        m = r.get("mira") or {}
        pred = m.get("predicate") or "—"
        dr = f"{m.get('domain','?')} → {m.get('range','?')}"
        w.append(f"| `{name}` | {pred} | {dr} | {r.get('cito') or '—'} | {r.get('dg') or '—'} |")
    w.append("")

    counts = {
        "a MIRA predicate": sum(1 for r in rels.values() if (r.get("mira") or {}).get("predicate")),
        "a CiTO term": sum(1 for r in rels.values() if r.get("cito")),
        "a Discourse Graphs term": sum(1 for r in rels.values() if r.get("dg")),
    }
    w.append("## Coverage")
    w.append("")
    for what, n in counts.items():
        w.append(f"- **{n} of {len(rels)}** have {what}.")
    w.append("")
    w.append("## Where a standard has no term, and why")
    w.append("")
    for name in sorted(rels):
        m = rels[name].get("mira") or {}
        if not m.get("predicate"):
            w.append(f"**`{name}`** — {m.get('note','')}")
            w.append("")
    w.append("## Namespaces")
    w.append("")
    for prefix, iri in sorted(standards.contexts().items()):
        w.append(f"- `{prefix}:` → {iri}")
    w.append("")
    return "\n".join(w)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true", help=f"write {os.path.relpath(OUT, MACHINERY)}")
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed copy is stale")
    a = ap.parse_args()
    text = render()
    if a.check:
        current = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if current != text:
            print(f"{os.path.relpath(OUT, MACHINERY)} is stale — "
                  f"run: python3 scripts/standards_report.py --write", file=sys.stderr)
            return 1
        print(f"{os.path.relpath(OUT, MACHINERY)}: current")
        return 0
    if a.write:
        with open(OUT, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {os.path.relpath(OUT, MACHINERY)}")
        return 0
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
